#!/bin/bash

source $HOME/.nvm/nvm.sh
current_version=$(nvm current)
current_v=${current_version:1}
requested_v=$NODEV
requested_len=${#requested_v}

if [[ ${current_v:0:requested_len} != $requested_v ]]; then
    nvm install ${NODEV} \
    && nvm use ${NODEV} \
    && nvm alias default $requested_v
fi
